"""V5.1a-next §G + §B(UI) — theme-layer and account-selector contracts.

§G: the generated utility layer must never paint a literal white background in the
dark V5 theme, and every class the source actually uses must have a rule. The
native `<select>`/`<option>` popup is the usual culprit (the browser paints it
white), so the stylesheet pins form controls to the theme's own surfaces.

§B(UI): the account selector exists once and is rendered by both MT5 pages, and it
is driven by the backend account API — no hard-coded account list, no invented
account numbers.
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
FRONTEND = REPO / "frontend"
SRC = FRONTEND / "src"
CSS = SRC / "styles.css"
SELECTOR = SRC / "components" / "Mt5AccountSelector.jsx"


def _gen():
    spec = importlib.util.spec_from_file_location("gen_theme_layer",
                                                  FRONTEND / "tools" / "gen_theme_layer.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _generated_block() -> str:
    text = CSS.read_text(encoding="utf-8")
    parts = text.split("/* ==== V5 UTILITY LAYER (generated by tools/gen_theme_layer.py) ==== */")
    assert len(parts) == 2, "the generated utility layer marker is missing"
    return parts[1]


# ===========================================================================
# §G — no white backgrounds, no unmapped classes
# ===========================================================================
def test_01_the_generated_layer_never_paints_a_white_background():
    block = _generated_block()
    bad = [rule for rule in re.findall(r"[^{}]+\{[^}]*\}", block)
           if re.search(r"background(?:-color)?\s*:\s*(#fff(?:fff)?|white|rgb\(255,\s*255,\s*255\))\s*;",
                        rule, re.I)]
    assert bad == [], f"white background rules emitted: {bad[:3]}"


def test_02_the_whole_stylesheet_has_no_white_element_background():
    """A white *element* fill is what makes text unreadable in this theme.

    (White text on the coloured buttons is fine and stays; a white surface behind
    theme-coloured text is not.)
    """
    text = CSS.read_text(encoding="utf-8")
    offenders = re.findall(r"([^{}\n]+)\{([^}]*background[^}]*)\}", text)
    bad = [sel.strip() for sel, body in offenders
           if re.search(r"background(?:-color)?\s*:\s*(#fff(?:fff)?|white|rgb\(255,\s*255,\s*255\))\b",
                        body, re.I)]
    assert bad == [], f"white background on: {bad[:5]}"


def test_03_bg_white_utility_resolves_to_the_v5_surface_not_white():
    gen = _gen()
    rule = gen.declaration("bg-white")
    assert rule is not None
    assert "#ffffff" not in rule.lower() and "white" not in rule.lower()
    assert "var(--panel2)" in rule


def test_04_text_white_is_still_allowed_for_coloured_buttons():
    gen = _gen()
    rule = gen.declaration("text-white")
    assert rule == "color: #ffffff;"


def test_05_form_controls_are_pinned_to_the_theme():
    text = CSS.read_text(encoding="utf-8")
    assert re.search(r"select,\s*option,\s*optgroup\s*\{[^}]*background:\s*var\(--panel2\)", text)
    assert re.search(r"option\s*\{[^}]*background:\s*var\(--panel\)", text)
    assert re.search(r"select\.input[^{]*\{[^}]*background:\s*var\(--bg2\)", text)


def test_06_every_class_used_in_the_source_is_mapped():
    """`gen_theme_layer.py --check` must report zero unmapped classes."""
    import subprocess
    out = subprocess.run(["/usr/bin/python3", str(FRONTEND / "tools" / "gen_theme_layer.py"),
                          "--check"], capture_output=True, text=True, cwd=str(FRONTEND))
    assert "unmapped: 0" in out.stdout, out.stdout + out.stderr


def test_07_the_generator_is_idempotent():
    import subprocess
    before = CSS.read_text(encoding="utf-8")
    subprocess.run(["/usr/bin/python3", str(FRONTEND / "tools" / "gen_theme_layer.py")],
                   capture_output=True, text=True, cwd=str(FRONTEND), check=True)
    after = CSS.read_text(encoding="utf-8")
    assert before == after, "re-running the generator changed the stylesheet"


# ===========================================================================
# §B(UI) — the account selector
# ===========================================================================
def test_08_the_selector_is_one_component_used_by_both_mt5_pages():
    assert SELECTOR.exists()
    for rel in ("pages/Mt5DemoTrading.jsx", "pages/LiveTesting.jsx"):
        src = (SRC / rel).read_text(encoding="utf-8")
        assert "Mt5AccountSelector" in src, rel
        assert "<Mt5AccountSelector" in src, rel


def test_09_the_selector_is_backend_driven():
    src = SELECTOR.read_text(encoding="utf-8")
    assert "api.mt5Accounts" in src and "api.mt5AccountSelect" in src
    # no hard-coded account list / account numbers
    assert not re.search(r"\b\d{7,}\b", src), "an account number appears to be hard-coded"


def test_10_a_real_account_stays_visibly_refused():
    src = SELECTOR.read_text(encoding="utf-8")
    assert "REAL ACCOUNT DETECTED — ORDERS ARE REFUSED." in src
    assert "does not make it tradable" in src or "the demo guard refuses" in src.lower()


def test_11_the_selector_never_claims_a_probe_or_a_trade_it_did_not_do():
    src = SELECTOR.read_text(encoding="utf-8")
    assert "never sends an order" in src
    assert "Accounts are not probed yet" in src          # the honest "not probed" state
    assert "not importable in this interpreter" in src    # the honest unavailable state


def test_12_the_api_client_exposes_the_new_endpoints():
    src = (SRC / "api.js").read_text(encoding="utf-8")
    assert "/api/mt5/accounts" in src
    assert "/api/mt5/accounts/select" in src
    assert "/api/nodes/populations" in src


def test_13_the_selector_uses_the_shared_kit_components():
    src = SELECTOR.read_text(encoding="utf-8")
    for sym in ("Card", "Badge", "StateBlock"):
        assert sym in src, sym
    # no invented class names: everything here is in the theme layer
    classes = set(re.findall(r'className="([^"]+)"', src))
    known = set(re.findall(r"\.([a-zA-Z][\w-]*)", CSS.read_text(encoding="utf-8")))
    unknown = {c for group in classes for c in group.split() if c not in known}
    assert unknown == set(), unknown
