#!/usr/bin/env python3
"""Generate the V5 utility layer from the *actual* class usage in frontend/src.

The MT5 Backtest / Live Test Results / MT5 Demo Trading screens are written with
Tailwind-style utility class names, but Tailwind is not installed in this project
so none of them had any CSS. This script reads every className in frontend/src,
keeps the ones the stylesheet does not define and that match the known utility
patterns, maps each onto an EXISTING V5 design token, and appends the result to
src/styles.css between explicit markers (so re-running is idempotent).

Run:  python3 tools/gen_theme_layer.py [--check]
      --check  only report what would be missing (exit 1 if any class is
               unmapped), without writing anything.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

FRONTEND = Path(__file__).resolve().parents[1]
SRC = FRONTEND / "src"
CSS = SRC / "styles.css"
BEGIN = "/* ==== V5 UTILITY LAYER (generated by tools/gen_theme_layer.py) ==== */"
END = "/* ==== end V5 utility layer ==== */"

# ---- token map: the V5 palette is the only source of colour ----------------- #
SLATE = {
    "950": "var(--bg)", "900": "var(--bg2)", "800": "var(--panel2)", "700": "#2f3a52",
    "600": "#5b6579", "500": "var(--muted)", "400": "#98a2b8", "300": "#b9c2d6",
    "200": "var(--text)", "100": "#e6ebf3", "50": "#f2f5fa",
}
ACCENT_SHADES = {
    # indigo/violet in the page markup = the V5 accent / violet
    "indigo": {"500": "var(--accent)", "600": "var(--accent)", "400": "#9dc0ff", "300": "#9dc0ff",
               "200": "#c3d8ff", "950": "#16233d", "900": "#1c2b4a", "800": "#233654", "700": "#2b4370"},
    "purple": {"500": "var(--violet)", "600": "#7c5cd0", "400": "var(--violet)", "300": "var(--violet)",
               "200": "#ddd2ff", "950": "#241c39", "900": "#2c2440", "800": "#3a3060", "700": "#4a3d78"},
    "violet": {"500": "var(--violet)", "400": "var(--violet)", "300": "var(--violet)"},
    "cyan": {"300": "var(--cyan)", "400": "var(--cyan)", "500": "var(--cyan)", "700": "#166a80"},
    "emerald": {"300": "var(--green)", "400": "var(--green)", "500": "#17805a", "600": "#10633f",
                "800": "#0d4a30", "950": "#0d2a1c"},
    "green": {"300": "var(--green)", "400": "var(--green)", "500": "#17805a", "600": "#10633f"},
    "rose": {"200": "#ffd5d5", "300": "var(--red)", "400": "var(--red)", "500": "var(--red)",
             "600": "#c9453f", "700": "#8f2f2f", "800": "#6f2626", "900": "#4a1d1d", "950": "#33181a"},
    "red": {"300": "var(--red)", "400": "var(--red)", "500": "var(--red)"},
    "amber": {"200": "#ffe0a3", "300": "var(--amber)", "400": "var(--amber)", "500": "var(--amber)",
              "600": "#8a6718", "700": "#7a5a16", "950": "#3a2c10"},
    "orange": {"200": "#ffe0a3", "300": "var(--amber)", "400": "var(--amber)",
               "500": "var(--amber)", "600": "#8a6718", "700": "#7a5a16", "950": "#3a2c10"},
    "yellow": {"300": "var(--amber)", "400": "var(--amber)"},
    "white": {}, "black": {}, "slate": SLATE,
}
FAMILY_OF = {name: name for name in ACCENT_SHADES}

def sp(value: str):
    """Tailwind's spacing scale: n = n * 4px (0.5 -> 2px, 1.5 -> 6px, 24 -> 96px)."""
    try:
        n = float(value)
    except ValueError:
        return None
    return f"{n * 4:g}px"
RADIUS = {"": "6px", "lg": "8px", "xl": "10px", "2xl": "14px", "full": "999px"}
SHADOWS = {"": "0 4px 14px rgba(0,0,0,.35)", "sm": "0 2px 8px rgba(0,0,0,.3)",
           "md": "0 6px 18px rgba(0,0,0,.35)", "lg": "0 12px 30px rgba(0,0,0,.4)",
           "xl": "0 16px 40px rgba(0,0,0,.45)", "2xl": "0 20px 50px rgba(0,0,0,.5)"}
FONT_SIZES = {"xs": "11.5px", "sm": "12.5px", "base": "14px", "lg": "16px", "xl": "18px",
              "2xl": "21px", "3xl": "24px"}
WEIGHTS = {"bold": "700", "extrabold": "800", "semibold": "600", "medium": "550", "light": "300"}
STEPS = {"1": "1", "2": "2", "3": "3", "4": "4", "6": "6", "8": "8", "12": "12"}
GRID_COLS = {str(n): str(n) for n in range(1, 13)}

# ---- the mapping ----------------------------------------------------------- #
def hex_rgb(value: str):
    """`#3a2c10` -> `58, 44, 16` so an /opacity utility keeps its alpha."""
    m = re.fullmatch(r"#([0-9a-fA-F]{6})", value or "")
    if not m:
        return None
    h = m.group(1)
    return f"{int(h[0:2], 16)}, {int(h[2:4], 16)}, {int(h[4:6], 16)}"


def escape(cls: str) -> str:
    return "".join(("\\" + ch) if ch in "[]/:.#%()" else ch for ch in cls)


def declaration(cls: str):
    """CSS declarations for a single utility class, or None if unknown."""
    if cls in ("flex",): return "display: flex;"
    if cls == "inline-flex": return "display: inline-flex;"
    if cls == "grid": return "display: grid;"
    if cls == "block": return "display: block;"
    if cls == "inline-block": return "display: inline-block;"
    if cls == "hidden": return "display: none;"
    if cls == "table": return None                      # component class, styled above
    if cls == "flex-col": return "flex-direction: column;"
    if cls == "flex-row": return "flex-direction: row;"
    if cls == "flex-wrap": return "flex-wrap: wrap;"
    if cls == "flex-1": return "flex: 1 1 0%;"
    if cls == "shrink-0": return "flex: 0 0 auto;"
    if cls == "items-center": return "align-items: center;"
    if cls == "items-start": return "align-items: flex-start;"
    if cls == "items-end": return "align-items: flex-end;"
    if cls == "items-baseline": return "align-items: baseline;"
    if cls == "justify-between": return "justify-content: space-between;"
    if cls == "justify-center": return "justify-content: center;"
    if cls == "justify-end": return "justify-content: flex-end;"
    if cls == "justify-start": return "justify-content: flex-start;"
    if cls == "text-right": return "text-align: right;"
    if cls == "text-left": return "text-align: left;"
    if cls == "text-center": return "text-align: center;"
    if cls == "uppercase": return "text-transform: uppercase;"
    if cls == "normal-case": return "text-transform: none;"
    if cls == "underline": return "text-decoration: underline;"
    if cls == "truncate": return "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"
    if cls == "break-words": return "overflow-wrap: anywhere; word-break: break-word;"
    if cls == "break-all": return "word-break: break-all;"
    if cls == "whitespace-normal": return "white-space: normal;"
    if cls == "whitespace-nowrap": return "white-space: nowrap;"
    if cls == "leading-none": return "line-height: 1;"
    if cls == "leading-relaxed": return "line-height: 1.6;"
    if cls == "tracking-wider": return "letter-spacing: 0.6px;"
    if cls == "tracking-wide": return "letter-spacing: 0.3px;"
    if cls == "tracking-tight": return "letter-spacing: -0.2px;"
    if cls == "w-full": return "width: 100%;"
    if cls == "h-full": return "height: 100%;"
    if cls == "mx-auto": return "margin-left: auto; margin-right: auto;"
    if cls == "ml-auto": return "margin-left: auto;"
    if cls == "overflow-hidden": return "overflow: hidden;"
    if cls == "overflow-x-auto": return "overflow-x: auto;"
    if cls == "overflow-y-auto": return "overflow-y: auto;"
    if cls == "border": return "border: 1px solid var(--border);"
    if cls == "border-0": return "border: 0;"
    if cls == "border-b": return "border-bottom: 1px solid var(--border);"
    if cls == "border-t": return "border-top: 1px solid var(--border);"
    if cls == "border-l": return "border-left: 1px solid var(--border);"
    if cls == "border-r": return "border-right: 1px solid var(--border);"
    if cls == "divide-y": return None                    # handled with its colour partner
    if cls == "fixed": return "position: fixed;"
    if cls == "absolute": return "position: absolute;"
    if cls == "relative": return "position: relative;"
    if cls == "inset-0": return "inset: 0;"
    if cls == "z-50": return "z-index: 50;"
    if cls == "backdrop-blur-sm": return "backdrop-filter: blur(3px);"
    if cls == "cursor-pointer": return "cursor: pointer;"
    if cls == "pointer-events-none": return "pointer-events: none;"
    if cls == "transition-colors": return "transition: color .15s ease, background-color .15s ease, border-color .15s ease;"
    if cls == "transition-all": return "transition: all .18s ease;"
    if cls in ("animate-in", "fade-in"): return "animation: kitfade .22s ease both;"
    if cls == "font-mono": return "font-family: var(--mono);"
    if cls == "font-sans": return "font-family: inherit;"

    # state variants: `disabled:opacity-40` -> `.disabled\:opacity-40:disabled`
    m = re.fullmatch(r"(hover|focus|active|disabled):(.+)", cls)
    if m:
        return ("VARIANT", m.group(1), declaration(m.group(2)))

    # vertical rhythm helper (`space-y-3` = every child but the first)
    m = re.fullmatch(r"space-y-(\d+(?:\.\d+)?)", cls)
    if m and sp(m.group(1)):
        return ("CHILDREN", f"margin-top: {sp(m.group(1))};")

    m = re.fullmatch(r"duration-(\d+)", cls)
    if m: return f"transition-duration: {int(m.group(1))}ms;"
    m = re.fullmatch(r"shadow(?:-(sm|md|lg|xl|2xl))?", cls)
    if m and m.group(1) in SHADOWS: return f"box-shadow: {SHADOWS[m.group(1)]};"
    if cls == "shadow": return f"box-shadow: {SHADOWS['']};"

    m = re.fullmatch(r"text-\[(\d+)px\]", cls)
    if m: return f"font-size: {m.group(1)}px;"
    m = re.fullmatch(r"text-(xs|sm|base|lg|xl|2xl|3xl)", cls)
    if m: return f"font-size: {FONT_SIZES[m.group(1)]};"
    m = re.fullmatch(r"font-(bold|extrabold|semibold|medium|light)", cls)
    if m: return f"font-weight: {WEIGHTS[m.group(1)]};"

    # spacing: p / px / py / pt / pb / pl / pr / m / mx / my / mt / mb / ml / mr
    m = re.fullmatch(r"(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr)-(\d+(?:\.\d+)?)", cls)
    if m and sp(m.group(2)) is not None:
        prop, val = m.group(1), sp(m.group(2))
        if prop == "p":  return f"padding: {val};"
        if prop == "px": return f"padding-left: {val}; padding-right: {val};"
        if prop == "py": return f"padding-top: {val}; padding-bottom: {val};"
        if prop == "pt": return f"padding-top: {val};"
        if prop == "pb": return f"padding-bottom: {val};"
        if prop == "pl": return f"padding-left: {val};"
        if prop == "pr": return f"padding-right: {val};"
        if prop == "m":  return f"margin: {val};"
        if prop == "mx": return f"margin-left: {val}; margin-right: {val};"
        if prop == "my": return f"margin-top: {val}; margin-bottom: {val};"
        if prop == "mt": return f"margin-top: {val};"
        if prop == "mb": return f"margin-bottom: {val};"
        if prop == "ml": return f"margin-left: {val};"
        if prop == "mr": return f"margin-right: {val};"

    # gaps
    m = re.fullmatch(r"gap-(x|y)?-?(\d+(?:\.\d+)?)", cls)
    if m and sp(m.group(2)) is not None:
        val = sp(m.group(2))
        axis = m.group(1)
        if axis == "x": return f"column-gap: {val};"
        if axis == "y": return f"row-gap: {val};"
        return f"gap: {val};"

    # grid columns (with optional responsive prefix)
    m = re.fullmatch(r"(?:sm:|md:|lg:|xl:)?grid-cols-(\d+)", cls)
    if m and m.group(1) in GRID_COLS:
        return f"grid-template-columns: repeat({m.group(1)}, minmax(0, 1fr));"
    m = re.fullmatch(r"(?:sm:|md:|lg:|xl:)?col-span-(\d+)", cls)
    if m: return f"grid-column: span {m.group(1)} / span {m.group(1)};"

    # sizes: w-N / h-N / max-w-* / max-h-* / min-w-[..]
    m = re.fullmatch(r"w-(\d+(?:\.\d+)?)", cls)
    if m and sp(m.group(1)) is not None: return f"width: {sp(m.group(1))};"
    if cls == "w-1/2": return "width: 50%;"
    if cls == "w-1/3": return "width: 33.3333%;"
    if cls == "h-1/2": return "height: 50%;"
    m = re.fullmatch(r"h-(\d+(?:\.\d+)?)", cls)
    if m and sp(m.group(1)) is not None: return f"height: {sp(m.group(1))};"
    m = re.fullmatch(r"min-w-\[(\d+)px\]", cls)
    if m: return f"min-width: {m.group(1)}px;"
    m = re.fullmatch(r"max-w-\[(\d+)px\]", cls)
    if m: return f"max-width: {m.group(1)}px;"
    for name, value in (("xs", "360px"), ("sm", "460px"), ("md", "560px"), ("lg", "640px"),
                        ("xl", "760px"), ("2xl", "860px"), ("3xl", "960px"), ("4xl", "1080px"),
                        ("5xl", "1200px"), ("6xl", "1320px"), ("7xl", "1440px"), ("full", "100%")):
        if cls == f"max-w-{name}": return f"max-width: {value};"
    for name, value in (("8", "32px"), ("12", "48px"), ("16", "64px"), ("20", "80px"), ("24", "96px"),
                        ("32", "128px"), ("36", "144px"), ("40", "160px"), ("48", "192px"),
                        ("56", "224px"), ("64", "256px"), ("72", "288px"), ("80", "320px"),
                        ("96", "384px"), ("full", "100%")):
        if cls == f"max-h-{name}": return f"max-height: {value};"

    # radii
    m = re.fullmatch(r"rounded(?:-(lg|xl|2xl|full))?", cls)
    if m and (m.group(1) or "") in RADIUS: return f"border-radius: {RADIUS[m.group(1) or '']};"
    if cls == "rounded-t": return "border-radius: 6px 6px 0 0;"
    if cls == "rounded-b": return "border-radius: 0 0 6px 6px;"

    # colours: bg-* / text-* / border-* / divide-*/hover:*/focus:*/disabled:*
    for prefix, prop in (("bg", "background-color"), ("text", "color"), ("border", "border-color"),
                         ("divide", "border-color"), ("ring", "box-shadow")):
        for variant in ("", "hover:", "focus:", "disabled:", "active:"):
            lead = variant + prefix + "-"
            if not cls.startswith(lead):
                continue
            rest = cls[len(lead):]
            if variant == "disabled:" and rest in ("opacity-40", "opacity-50", "opacity-60"):
                return f"opacity: {int(rest.split('-')[1]) / 100};"
            if variant == "disabled:" and rest == "cursor-not-allowed":
                return "cursor: not-allowed;"
            if variant == "focus:" and rest in ("outline-none",):
                return "outline: none;"
            if variant == "focus:" and rest.startswith("border-"):
                rest2 = rest[len("border-"):]
                fam, _, shade = rest2.rpartition("-")
                val = ACCENT_SHADES.get(fam, {}).get(shade)
                if val: return f"border-color: {val};"
                continue
            if variant == "hover:" and rest.startswith("underline"):
                return "text-decoration: underline;"
            if variant == "hover:" and rest == "text-white":
                return "color: #fff;"
            # bg-slate-950/60  ·  text-slate-300  ·  border-rose-700/40
            op = None
            m = re.fullmatch(r"([a-z]+)-([0-9]+)(?:/(\d+))?", rest)
            if m:
                fam, shade, op = m.group(1), m.group(2), m.group(3)
            else:
                m = re.fullmatch(r"(white|black)(?:/(\d+))?", rest)
                if m:
                    fam, shade, op = m.group(1), None, m.group(2)
            if fam is None:
                continue
            if fam in ("white", "black") and shade is None:
                base = "#ffffff" if fam == "white" else "#000000"
            else:
                base = ACCENT_SHADES.get(fam, {}).get(str(shade))
            if base is None:
                continue
            if op is not None:
                alpha = int(op) / 100 if int(op) <= 100 else 1.0
                rgb = TOKEN_RGB.get(base) or hex_rgb(base)
                value = f"rgba({rgb}, {alpha})" if rgb else base
            else:
                value = base
            if prefix == "divide":
                return None                      # handled by the divide-y rule below
            return f"{prop}: {value};" + (" !important" if variant == "hover:" and prefix == "bg" else "")

    return None


# rgba() needs numeric channels; map the V5 tokens we know
TOKEN_RGB = {
    "var(--bg)": "11, 14, 20", "var(--bg2)": "17, 21, 31", "var(--panel)": "21, 26, 38",
    "var(--panel2)": "27, 33, 48", "var(--border)": "35, 43, 61", "var(--accent)": "79, 142, 247",
    "var(--green)": "52, 211, 153", "var(--red)": "248, 113, 113", "var(--amber)": "251, 191, 36",
    "var(--violet)": "167, 139, 250", "var(--cyan)": "34, 211, 238", "var(--muted)": "139, 147, 167",
    "var(--text)": "215, 220, 230",
}


# page-level hooks that pages already reference: themed as the standard V5
# page container / header / panel instead of leaving them unstyled
SEMANTIC = {
    "mt5-backtest-page": "display: block;",
    "mt5-demo-page": "display: block;",
    "final-testing-page": "display: block;",
    "activity-page": "display: block;",
    "page-header": ("display: flex; align-items: flex-end; justify-content: space-between; "
                    "gap: 12px; flex-wrap: wrap; margin-bottom: 14px;"),
    "current-task-box": ("background: var(--panel2); border: 1px solid var(--border); "
                         "border-radius: 8px; padding: 9px 11px; font-size: 12px;"),
    "milestone-route-container": "display: flex; gap: 8px; flex-wrap: wrap; align-items: center;",
    "live-activity-panel": ("background: var(--panel); border: 1px solid var(--border); "
                            "border-radius: 10px; padding: 12px;"),
    "live-activity-sidebar": ("background: var(--bg2); border-left: 1px solid var(--border); "
                              "padding: 12px; display: flex; flex-direction: column; gap: 10px;"),
    "live-activity-collapsed-strip": ("display: flex; align-items: center; gap: 8px; "
                                      "background: var(--panel2); border: 1px solid var(--border); "
                                      "border-radius: 8px; padding: 6px 10px; font-size: 11.5px;"),
    "activity-stream-scroll": "max-height: 420px; overflow-y: auto;",
}
# names that are state flags / dynamic expressions, never standalone classes
DYNAMIC_EXTRA = {
    "activeFilter", "detailTab", "modeTone", "gpuToggle", "shortlistOnly", "isRunning",
    "allowed", "connected", "activePopover", "cat", "isStar", "status", "ok", "net_profit",
    "requireText", "population", "source", "is_stalled", "promoted_to_paper", "SHORTLISTED",
    "s", "tone",
}


def used_classes() -> "set[str]":
    used = set()
    for path in list(SRC.rglob("*.jsx")) + list(SRC.rglob("*.js")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'className=(?:"([^"]*)"|\{`([^`]*)`\}|\{"([^"]*)"\})', text):
            raw = m.group(1) or m.group(2) or m.group(3) or ""
            for tok in re.split(r"[\s${}]+", raw):
                tok = tok.strip()
                if re.fullmatch(r"[a-zA-Z][-a-zA-Z0-9_:./\[\]]*", tok) and not tok.startswith("https"):
                    used.add(tok)
    return used


def handwritten_css() -> str:
    """The stylesheet WITHOUT this generator's own block (keeps the run idempotent)."""
    text = CSS.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        text = text[:text.index(BEGIN)] + text[text.index(END) + len(END):]
    return text


def defined_classes() -> "set[str]":
    return set(re.findall(r"\.((?:[a-zA-Z0-9_-]|\\.)+)", handwritten_css()))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    css_text = handwritten_css().rstrip("\n") + "\n"
    defined = defined_classes()
    used = used_classes()

    # classes that are dynamic expressions leaked by the regex - never real class names
    dynamic = {c for c in used if re.search(r"[.=()\[\]]", c) and not c.startswith(("text-[", "max-w-", "min-w-"))}
    dynamic |= {c for c in used if c in {
        "tone", "isRunning", "allowed", "connected", "activePopover", "detailTab", "cat", "isStar",
        "status", "ok", "net_profit", "requireText", "population", "source", "is_stalled",
        "promoted_to_paper", "SHORTLISTED", "s", "ghost", "primary", "danger", "success", "warn",
        "mute", "info", "accent", "sim", "real", "violet", "good", "bad", "compact", "table",
        "num", "clickable", "selected", "is-selected", "input", "field", "stack", "row-bar",
        "spacer", "page", "chk", "cols-5", "cols-6", "top-status-row", "table-wrap", "scroll-x",
        "kit-col", "kit-grid", "kit-kpi-row", "kit-pager", "kit-inline-ok", "kit-summary",
        "error-note", "modal-content", "status-pill", "status-row-item", "panel-title",
        "section-title", "metric-grid", "btn-sm", "btn-xs", "btn-subtle", "btn-primary", "btn-icon",
        "icon", "sm", "xs", "lg", "xl",
    }}

    dynamic |= DYNAMIC_EXTRA
    missing = sorted(c for c in used if c not in defined and c not in dynamic and c not in SEMANTIC)
    rows: "list[tuple[str, object]]" = []
    unmapped: "list[str]" = []
    for cls in missing:
        decl = declaration(cls)
        if decl is None:
            # `divide-y` + `divide-<colour>` are emitted as child-selector rules
            if cls in ("divide-y", "table") or cls.startswith("divide-"):
                continue
            unmapped.append(cls)
        else:
            rows.append((cls, decl))

    # the divide-* family: a single rule that uses the colour of its partner class
    divide_rules = []
    if any(c.endswith("divide-slate-800/60") for c in used):
        divide_rules.append(".divide-slate-800\\/60 > * + * { border-top: 1px solid rgba(35, 43, 61, .6); }")
    if any(c.endswith("divide-rose-800/60") for c in used):
        divide_rules.append(".divide-rose-800\\/60 > * + * { border-top: 1px solid rgba(111, 38, 38, .6); }")

    print(f"used: {len(used)}  defined: {len(defined)}  to generate: {len(rows)}  unmapped: {len(unmapped)}")
    if unmapped:
        print("UNMAPPED (no rule will be emitted):")
        for c in sorted(set(unmapped)):
            print(f"   {c}")
    if args.check:
        return 1 if unmapped else 0

    lines = []
    for cls, decl in sorted(rows):
        if isinstance(decl, tuple):
            if decl[0] == "VARIANT":
                state, inner = decl[1], decl[2]
                if isinstance(inner, tuple):            # e.g. disabled:cursor-not-allowed
                    inner = inner[1] if inner[0] == "CHILDREN" else None
                if inner:
                    lines.append(f".{escape(cls)}:{state} {{ {inner} }}")
            elif decl[0] == "CHILDREN":
                lines.append(f".{escape(cls)} > * + * {{ {decl[1]} }}")
        else:
            lines.append(f".{escape(cls)} {{ {decl} }}")
    lines.append("@keyframes kitfade { from { opacity: 0; transform: translateY(2px); } "
                 "to { opacity: 1; transform: none; } }")
    body = "\n".join(lines)
    section = f"\n{BEGIN}\n{body}\n" + ("\n".join(divide_rules) + "\n" if divide_rules else "") + f"{END}\n"

    # idempotent: replace the previous generated block if present
    if BEGIN in css_text and END in css_text:
        start = css_text.index(BEGIN)
        stop = css_text.index(END) + len(END) + 1
        css_text = css_text[:start] + section.lstrip("\n") + css_text[stop:]
    else:
        css_text = css_text.rstrip("\n") + "\n" + section
    CSS.write_text(css_text, encoding="utf-8")
    print(f"wrote {len(rows)} utility rules into {CSS.name} (+{len(divide_rules)} divide rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
