"""Runtime identity — proof of *which process* is answering the dashboard.

The launcher (``start.bat``) must never assume that "something answered
``/health`` on 8787" means "the current build is being served". A backend that
was started before a rebuild, or from an older checkout, will happily keep
serving *old Python code* while the files on disk say FRESH — which is exactly
how a stale dashboard survives a successful rebuild.

This module makes the running process describe itself, so the launcher can
compare three things that must all agree:

    source on disk  ==  the code this process was started from
    bundle on disk  ==  the bundle this process was started with
    this process    ==  the process the launcher just started (start token)

Nothing here is persisted, guessed or configured: every value is measured from
the running process and the files next to it. The token is generated by the
launcher per launch and passed through the environment, so it proves *this*
process was started by *that* launch (an inherited variable cannot survive a
process restart).

No secrets are involved: the token is a per-launch nonce, and the fingerprints
are plain content hashes of files that are already in the repository.
"""
from __future__ import annotations

import hashlib
import os
import platform
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# --------------------------------------------------------------------------- #
# process birth — captured when this module is first imported by the backend
# --------------------------------------------------------------------------- #
PROCESS_STARTED_AT: float = time.time()
PROCESS_PID: int = os.getpid()

#: Set by the launcher for each launch (``start.bat`` exports it before the
#: backend process is created). ``None`` when the backend was started by hand.
START_TOKEN: Optional[str] = (os.environ.get("EVOLUTIONARY_LAB_START_TOKEN") or "").strip() or None

#: Why/where this process was started from, if the launcher said so.
START_MODE: Optional[str] = (os.environ.get("EVOLUTIONARY_LAB_START_MODE") or "").strip() or None

_CODE_CACHE: Dict[str, Any] = {}
_SNAPSHOT: Optional[Dict[str, Any]] = None

#: Directories that are part of "the code this process runs". Kept in step with
#: the launcher's expectation: Python that can change behaviour.
CODE_DIRS = ("app",)


def _root() -> Path:
    from . import paths as P
    return Path(P.ROOT_DIR)


def frontend_dist_dir(root: Optional[Path] = None) -> Path:
    """The one and only production bundle directory of this repository."""
    return (Path(root) if root is not None else _root()) / "frontend" / "dist"


def code_fingerprint(root: Optional[Path] = None) -> Dict[str, Any]:
    """Content hash of the backend source tree this process is running.

    The launcher computes the *same* fingerprint from the checkout on disk. If
    the two differ, the process in front of the operator was started from
    different code than the code on disk — a stale process, whatever the
    filesystem or the build stamp says.
    """
    root = Path(root) if root is not None else _root()
    key = str(root)
    if key in _CODE_CACHE:
        return _CODE_CACHE[key]
    h = hashlib.sha256()
    files = 0
    base = root / "backend"
    for sub in CODE_DIRS:
        d = base / sub
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*.py")):
            if "__pycache__" in p.parts:
                continue
            try:
                h.update(p.relative_to(base).as_posix().encode("utf-8"))
                h.update(b"\0")
                h.update(p.read_bytes())
                h.update(b"\0")
                files += 1
            except OSError:
                continue
    info = {"code_hash": h.hexdigest(), "code_files": files, "base": str(base)}
    _CODE_CACHE[key] = info
    return info


def _bundle_state(dist: Path) -> Dict[str, Any]:
    """Which bundle is on disk right now (read fresh, like the static mount does)."""
    index = dist / "index.html"
    out: Dict[str, Any] = {"bundle_dir": str(dist), "index_sha256": None,
                           "entry_assets": [], "index_exists": index.is_file()}
    if not index.is_file():
        return out
    try:
        out["index_sha256"] = hashlib.sha256(index.read_bytes()).hexdigest()
    except OSError:
        pass
    assets: List[str] = []
    try:
        text = index.read_text(encoding="utf-8", errors="replace")
    except OSError:
        text = ""
    import re
    for m in re.finditer(r'(?:src|href)="([^"]+\.(?:js|css))"', text):
        rel = m.group(1).lstrip("/")
        assets.append(rel)
    out["entry_assets"] = sorted(set(assets))
    return out


def snapshot(refresh: bool = False) -> Dict[str, Any]:
    """The state this process was *born with* — captured once, then frozen.

    The snapshot is what makes staleness detectable: if the bundle on disk no
    longer matches the snapshot, this process has survived a rebuild and is no
    longer the instance the current build produced.
    """
    global _SNAPSHOT
    if _SNAPSHOT is not None and not refresh:
        return _SNAPSHOT
    dist = frontend_dist_dir()
    code = code_fingerprint()
    _SNAPSHOT = {
        "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "code_hash": code["code_hash"],
        "code_files": code["code_files"],
        "bundle": _bundle_state(dist),
    }
    return _SNAPSHOT


def served_now() -> Dict[str, Any]:
    """Which bundle this process would serve for a *new* request (from disk)."""
    disk = _bundle_state(frontend_dist_dir())
    snap = snapshot()
    loaded = snap.get("bundle") or {}
    disk["changed_since_start"] = bool(
        disk.get("index_sha256") and loaded.get("index_sha256")
        and disk["index_sha256"] != loaded["index_sha256"])
    disk["loaded_index_sha256"] = loaded.get("index_sha256")
    disk["loaded_entry_assets"] = loaded.get("entry_assets") or []
    disk["current_code_hash"] = code_fingerprint()["code_hash"]
    disk["code_changed_since_start"] = disk["current_code_hash"] != snap.get("code_hash")
    return disk


def process_identity(include_argv: bool = False) -> Dict[str, Any]:
    """Identity of THIS process — enough for the launcher to prove it is talking
    to the instance it started, and to the code/bundle that are on disk."""
    now = time.time()
    snap = snapshot()
    ident: Dict[str, Any] = {
        "pid": PROCESS_PID,
        "started_at": round(PROCESS_STARTED_AT, 3),
        "started_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(PROCESS_STARTED_AT)),
        "uptime_s": round(max(0.0, now - PROCESS_STARTED_AT), 1),
        "start_token": START_TOKEN,
        "start_mode": START_MODE,
        "code_hash": snap["code_hash"],
        "code_files": snap["code_files"],
        "python": platform.python_version(),
        "executable": sys.executable,
        "cwd": os.getcwd(),
    }
    if include_argv:
        ident["argv"] = list(sys.argv)
    return ident


def identity_report(serving: str, root: Optional[Path] = None) -> Dict[str, Any]:
    """The runtime half of ``GET /system/build`` (the filesystem half stays in
    ``frontend_build.served_payload``). Never contains secrets."""
    root = Path(root) if root is not None else _root()
    from .frontend_build import check_dist, _sha256_file  # noqa: PLC2701 - shared hashing
    from .versions import APP_VERSION, FULL_VERSION_STRING, PRODUCT_RELEASE, git_hash

    dist = frontend_dist_dir(root)
    loaded = snapshot()["bundle"]
    disk = served_now()
    served_index = _sha256_file(dist / "index.html") if (dist / "index.html").is_file() else None
    return {
        "app": "EVOLUTIONARY TRADING RESEARCH LAB",
        "release": PRODUCT_RELEASE,
        "version": APP_VERSION,
        "version_string": FULL_VERSION_STRING,
        "git_commit": git_hash() or None,
        "repo_root": str(root),
        "serving": serving,
        "process": process_identity(),
        "loaded": {
            "captured_at": snapshot()["captured_at"],
            "bundle_dir": loaded.get("bundle_dir"),
            "index_sha256": loaded.get("index_sha256"),
            "entry_assets": loaded.get("entry_assets") or [],
        },
        "served": {
            "bundle_dir": disk.get("bundle_dir"),
            "index_sha256": served_index,
            "entry_assets": disk.get("entry_assets") or [],
            "changed_since_start": disk.get("changed_since_start"),
            "code_changed_since_start": disk.get("code_changed_since_start"),
        },
        "dist_status": check_dist(root)["status"],
    }
